services:
  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede   # conecta na rede já existente

volumes:
  pgdata:

networks:
  minha-rede:
    external: true   # avisa que a rede já existe
